### ISSUE TITLE
Communication for short time

### ISSUE THREAD

**Issue by bebehei** [bebehei/rsnapshot#1]
I've enabled here in my fork-repo the issues-section, that we can discuss futher without having the hassle of rsnapshot-discuss or the moderated list rsnapshot-maintainers. @myrdd @sam-at-github

**Comment by bebehei** [comment]
> @bebehei Good find on the call out for new maintainers email. I didn't catch this on the general mailing list. Wonder if it was ever posted there?

It was posted on rsnapshot-maintainers. It is moderated. There are only few persons: http://sourceforge.net/p/rsnapshot/mailman/rsnapshot-maintainers/thread/20141014160734.GA8275%40bytemark.barnyard.co.uk/#msg32930724

> But briefly, the situation with this repo, is that there is one tagged commit 1.3.1, which I'll assume is what most apt based repos are packaging off (its what is on stable debian repos at least). There is a significant number of commits (around 50) after that tag (from 2008) with no version bumps (no tags). This makes things hard (at least appears to). All the changes in those commits are untested, and someone - the maintainer going forward - is going to have to understand what they are, how to deal with them all. Are they backward compatible? Are they new features? Having said that they don't look all that major.
> 
> Then again the rsnapshot source code is a bit hairy.

It's perl ;-) I think it is very well written.

> I have no real interest in maintaining rsnapshot. I personally don't have any big ideas for future development either. I like it that way it is, except for the bugs and odd and end that could be improved. But I will definitely help out and stay tuned.
> 
> My opinion on what needs to happen:
> - Make github the primary focus. Mirror to source forge if you want. I would forget the rest.

This will be quite easy, the only hassle what you will have is finding a new home of rsnapshot-discuss. This list is quite populated in comparison to the rest of the project.

> - Start using gitflow development model very next thing.

Using gitflow: jep! 

> I would actually rebase master to 1.3.1. and take HEAD, as the new dev branch.

What do you mean with that? I can't imagine what you intend to.

> - tidy the source code, write a coding std, write a CONTRIBUTING.md that refers to the coding std, outlines how to run the tests, and encourages writing tests (I already tried to PR such along time ago).

The maintainers did not do anything. That is the reason. They may had not have the time to review those all.

> - Figure out WTF those 50 odd commits did, decide if they can all go in a single minor version, or how to cut them up. Then start tagging releases and merging them into master.

The next release of rsnapshot won't be a classical minor-release, I know! But we have to do it. IMO it is too much effort giving out 10 releases in a week, just to have the commits separated. Nobody will use the intermediate versions. They all skip the them and jump to the latest. We have to test the next release very hard!

**Comment by bebehei** [comment]
@sam-at-github If you look into my repo now, I've made 2 branches almost possible to merge together. The cleanup makes a radicale cleanup, the bugfix merges about Half of the Pull Requests (I cherry-picked them).

**Comment by sgpinkus** [comment]
On the rsnapshot-discuss mailing. Your right. Anyway I don't think its
that much work to maintain a source forge mirror, if only for the sake
of the mailing list.

> It's perl ;-) I think it is very well written.
> 
> Each to his own :). I used to be a Perl dev, for a while, but not for a
> while.  Good to know you like Perl anyway.
> 
> Using gitflow: jep!
> 
> ```
> I would actually rebase master to 1.3.1. and take HEAD, as the new
> dev branch.
> ```
> 
> What do you mean with that? I can't imagine what you intend to.
> 
> I mean: `git checkout master; git branch dev; git reset --hard 1.3.1;`.
> Yes this rewinds master, but from what I gather no downstream
> maintainers are using anything above 1.3.1 (maybe some of them have
> applied there own minor patches). Master is supposed to represent the
> last stable release. But historically it never has been in this project.
> So this is like resetting thing to the way they should be. Only thing
> is, there should have been a number of minor releases in there, so that
> needs to be rectified:
> 
> The next release of rsnapshot won't be a classical minor-release, I
> know! But we have to do it. IMO it is too much effort giving out 10
> releases in a week, just to have the commits separated. Nobody will
> use the intermediate versions. They all skip the them and jump to the
> latest. We have to test the next release very hard!
> 
> Thing is, I can see downstream maintainers have asked for specific
> issues to be fixed and specifically for a new release to be tagged with
> just that fix in it. So I was thinking, just cherry-pick the easy, low
> risk ones that people, especially downstream maintainers are asking for
> to start with. I think they will use the intermediate versions.

Having said that I'm not accross the code, and what is fixed in those 50
odd commits like you seem to be @bebehei.  If it makes sense to do most
of that in one big release then so be it. I'll take a look at your
cherry picking, but right now I'm thinking prioritize, and do small
bites size chunks. Remember how risk averse the current / currently awol
maintainers of rsnapshot are. I think it will also reduce the testing
burden building up test cases incrementally.

Also in terms of forking rsnapshot. Still thinking it should remain
where it is, but if the downstream maintainers for debian say, started
pull from you fork I think that would essentially make it the new official.

P.S. Downstream maintainers asking for version bumps for minor issues:
- http://sourceforge.net/p/rsnapshot/mailman/message/33125863/
- https://github.com/DrHyde/rsnapshot/issues/8

P.P.S. Dont have too much time to spend on this right now, but will try to
at least catch up with whats going on everyday and chime in.

Regards.

**Comment by sgpinkus** [comment]
Ok so those bug fixes look about right. I would include the ssh_args bug too as that keep on comming up. But again, IMO I feel we need to rebase master to 1.3.1 and not start from HEAD. To be honest Someone just needs to commit to being maintainer and bring it up on the mailing list. I can't see this going much further without discussing it on the mailing list. Cheers.

**Comment by sgpinkus** [comment]
Oh wait you do have the ssh_args one in there, my bad.

**Comment by bebehei** [comment]
> On the rsnapshot-discuss mailing. Your right. Anyway I don't think its
> that much work to maintain a source forge mirror, if only for the sake
> of the mailing list.

`git stash` # i think we should focus the code at first, we neiter got the
permission to change that

> > What do you mean with that? I can't imagine what you intend to.
> > 
> > I mean: `git checkout master; git branch dev; git reset --hard 1.3.1;`.

Right now, we there are about 90 commits to procede between master and
1.3.1 creating a diff of ~3000 lines.

> Yes this rewinds master, but from what I gather no downstream
> maintainers are using anything above 1.3.1 (maybe some of them have
> applied there own minor patches). Master is supposed to represent the
> last stable release. But historically it never has been in this project.

There is nothing released higher than 1.3.1. But AFAIK there are
patchsets, which found their way into distribution-packages (like in
Debian).

> Also in terms of forking rsnapshot. Still thinking it should remain
> where it is, but if the downstream maintainers for debian say, started
> pull from you fork I think that would.

Full ACK. I never intended to fork rsnapshot. Right now I make changes in
my own repo and I hope they get merged back!

**Comment by bebehei** [comment]
Ok, as you might have seen, I did not do anything to this repo here. I'm waiting for an answer of the Dev-Team. If I have got one, I will proceed working on it.

**Comment by bebehei** [comment]
this post is only used for notation of bug-trackers and distribution-specific patches
maintainence in distributions:
Fedora:
- http://pkgs.fedoraproject.org/cgit/rsnapshot.git/log/
  Debian:
- https://packages.debian.org/source/sid/rsnapshot
- http://anonscm.debian.org/cgit/collab-maint/rsnapshot.git
  Ubuntu:
- https://launchpad.net/ubuntu/+source/rsnapshot/
- https://bugs.launchpad.net/ubuntu/+source/rsnapshot/

**Comment by bebehei** [comment]
Good News, I've got now write access to rsnapshot main repo! Info follows later these days.

**Comment by sgpinkus** [comment]
Wow! Good work :).

**Comment by bebehei** [comment]
I hope, some people will care about the project by now. I will start proposing your way to make relases on the rsnapshot-maintainers-mailinglist. I hope they we'll accept, that we do the work, commiting about 90 commits again.

Then we will start pushing out patch-releases, that the distros take over the patches.

I'm now half-way through writing a Contributing.md, which gives a guidline how to add PRs and make releases.

It would be cool, if you subscribe to rsnapshot-maintainers, too. Sadly the archives on sourceforge only get updated 2 times a week and not by every mail.

**Comment by sgpinkus** [comment]
I will subscribe, but can't guarantee they will accept. Will be interesting to see what their thoughts are on how to move forward.

**Comment by myrdd** [comment]
Great work @bebehei! What you've discussed so far in this issue seems good to me. Also I didn't know gitflow so far; I think it's a great concept!
I try to keep up-to-date, but you can't expect significant work from me in the next few months..

**Comment by bebehei** [comment]
> Great work @bebehei! What you've discussed so far in this issue seems good to me. Also I didn't know gitflow so far; I think it's a great concept!

Thanks. 

Yep, many things did not find its way into repo here. Its main reason is that almost no development is done the last 6 years. IMHO the code looks quite good (I've seen worse). We have to use this basis and go forward. In my eyes, the work, which has to be done, is mainly organising the project. IMO Code and bugfixes follow automagically, if the project-environment is well designed. I'm not a perl expert and I won't push code-quality of the file rsnapshot-program.pl, but I will do for the whole environment. My intention now is not to write new code for rsnapshot, it is mainly organising the project, testing the changes and bugfixes and release them, that the distros overtake it.

**Comment by myrdd** [comment]
@bebehei do you have any plans on unit tests so far? I've got the impression that some option combinations, which are less frequently used, contain bugs. I'm currently discovering one of them and I thought it would be great (but of course a lot of work) if any combination of possible options would get tested.

Besides testing configuration options and their combinations, we could also test whether rsnapshot behaves well in case external commands fail.

More in general, I'm wondering how to unit test different environments, for example
- mounting/unmounting different filesystems
- LVM snapshotting
- etc.

Should the unit tests run in a virtual machine? Are several VMs needed? Could Docker be useful? (I have no experience with Docker, I've just heard about it.)

**Comment by bebehei** [comment]
I did not made any thoughts about unit-tests so far. kevinlyles made PR drhyde/rsnapshot#36 with adding some tests. He may have made some thoughts about it. I'm finishing an e-mail to rsnapshot-discuss right now and finish CONTRIBUTING.md. If you have anything to say about unit-tests, do it! Open an issue/PR/whatever and work on it. I won't give you any reglementations.

Sorry, I promised the mail on friday, but I had been sick this weekend. I have slept almost the whole weekend.

> Should the unit tests run in a virtual machine? Are several VMs needed? Could Docker be useful? (I have no experience with Docker, I've just heard about it.)
> What about travis CI? AFAIK Travis is also running tests. We don't need Travis, to distinguish if rsnapshot is building well.

Docker requires, that you have to build up your own environment. I don't want to do this.

**Comment by myrdd** [comment]
Thanks for the info about the PR by @kevinlyles. I think I have to understand the build system and read the existing unit tests before I can really discuss and argue about unit tests.

> What about travis CI?

I did not know that service, but using such a continuous integration service might be a good option.

@bebehei I hope you feel better soon, or now already!

**Comment by bebehei** [comment]
So I've written CONTRIBUTING.md. If you could review it, this would be a pleasure! This is probably not finished, but I hope for the comments from you.
https://github.com/bebehei/rsnapshot/blob/cleanup/CONTRIBUTING.md

@myrdd yes, I've recovered almost.

**Comment by myrdd** [comment]
@bebehei I've taken a look at the file. See https://github.com/myrdd/rsnapshot/commit/554b16efa22d07144599f635ec11c0dd4916c8c8

Some more comments:

> Keep in mind, that you have to execute `./autoclean.sh` before you commit.

Why not use a `.gitignore` file? [Documentation](http://git-scm.com/docs/gitignore). The existing `.cvsignore` could be removed if SVN is not used anymore.

> If you checked rsnapshot out of the git-repository, you have to generate the configure-script with:

In which cases it's not necessary to run `./autogen.sh`?

More comments:
- Should the release branches be named `release-x-y` or `release-x.y`? I think it should be consistent.
- FYI, the versioning you want is probably http://semver.org/, no?

**Edit:** See also https://github.com/myrdd/rsnapshot/commit/0bc4889c1678a7749099b98f586ec347aa85682a and decide how you want to display the list.

**Comment by sgpinkus** [comment]
:+1: for Travis CI, it should be very easy to setup up - although maybe not needed so much in a simple program  like rsnapshot. @bebehei The contributing is pretty good. Do you need to mention coding standards though?

**Comment by bebehei** [comment]
On January 26, 2015 8:55:21 PM CET, Martin Kimmerle notifications@github.com wrote:

> @bebehei I've taken a look at the file. See
> https://github.com/myrdd/rsnapshot/commit/554b16efa22d07144599f635ec11c0dd4916c8c8

I'm on my mobile right now. Changes look good. I hope you didn't copy the whole git history, cause my history done there is proper shit.

> Some more comments:
> 
> > Keep in mind, that you have to execute `./autoclean.sh` before you
> > commit.
> 
> Why not use a `.gitignore` file?
> [Documentation](http://git-scm.com/docs/gitignore). The existing
> `.cvsignore` could be removed if SVN is not used anymore.

Is there still a .cvsignore? Lol, this has to get removed, too. I haven't implemented the .gitignore because I did not find any stable pattern to distinguish no-to-use files. IMO the Makefile has to get cleaned up, before a gitignore makes sense.

> > If you checked rsnapshot out of the git-repository, you have to
> > generate the configure-script with:
> 
> In which cases it's not necessary to run `./autogen.sh`?

When you will get a release-tarball. This section about building should move into Readme but I did not want to change it now.

> More comments:
> - Should the release branches be named `release-x-y` or `release-x.y`?
>   I think it should be consistent.

Jupp, will change that. Thanks.

> - FYI, the versioning you want is probably http://semver.org/, no?

A bit. Semantic versioning says only, that a diff of 1.2.3 and 1.2.4 contains only bugfixes. In our case it is right, but i want - to take care about the "super-active" development of the last years and force them to make on every bugfix a new release.

**Comment by bebehei** [comment]
On January 26, 2015 9:10:38 PM CET, sam-at-github notifications@github.com wrote:

> :+1: for Travis CI, it should be very easy to setup up.

Jep, this will be a TODO. But I hope they answer my mail. I proposed today, that we could move the rsnapshot-repo to a github-organisation. After that we can deploy Travis.

> @bebehei The contributing is pretty good.

Thanks, @myrdd has an even better one! ;-)

> Do you need to mention coding standards though?

If you could mention it, edit it. I would not know what to mention there. In rsnapshot-preamble.pl there is no proper indentation-rule to follow. About programming-standards I haven't thought about it.

**Comment by myrdd** [comment]
> i want - to take care about the "super-active" development of the last years and force them to make on every bugfix a new release.

good to know.

I see you're using email to answer to comments. Note that I've edited my comment:

> Edit: See also myrdd@0bc4889 and decide how you want to display the list.

**Comment by bebehei** [comment]
That the you guys outside of rsnapshot-maintainers know what's going on: This is what I've written to the list today/a few hours ago:

> Hi,
> 
> now it's about getting forward and making releases. I've written a
> CONTRIBUTING.md[0] which I want to add to rsnapshot. This file should
> describe in general how development work is done and how releases are
> made. It is based on NOTES/\* and README.developers. I'm pleased, if you
> could review the file.
> 
> In regard of making new releases, there are a some possible ways to go:
> - Release now the whole Code with a bit testing as version 1.4. For me,
>   this seems to be the easier way, but the code is untested and I think
>   nobody really knows what impact of this will be. Anyway Distros like
>   Debian won't take this over to use it in their package, as this release is
>   not only containing bugfixes.
> - Release the code bit by bit. Branch out "dev" out of the release-commit
>   of 1.3.1. Reorganise the master-branch (by cherry-picking the commits
>   splitting them into seperate branches, as I have described it in
>   CONTRIBUTING.md. Then merge the bugfix-branches into release-1-3 and dev,
>   and the feature-enhancements only onto dev. After we merged all
>   feature-branches we will prepare to do a new release 1.4, which includes
>   these tested features. Between master and 1.3.1 are exactly 90 commits,
>   that's reasonable work.
> 
> I personally favor the 2nd approach. It will be more work, but I don't
> hesistate to do this. So we are able to release patches for the old 1.3,
> where people still have trouble with and the distros take the
> 1.3.x-releases over.
> 
> There is something else: Does anyone mind, if we move the repository over
> to a github-organisation[1]?
> 
> Cheers,
> Bene
> 
> [0] https://github.com/bebehei/rsnapshot/blob/cleanup/CONTRIBUTING.md
> [1] https://github.com/blog/674-introducing-organizations

@myrdd This may be interesting for your bug-report drhyde/rsnapshot#48

**Comment by sgpinkus** [comment]
> If you could mention it, edit it. I would not know what to mention there. In rsnapshot-preamble.pl there is no proper indentation-rule to follow. About programming-standards I haven't thought about it.

Added a (rough) section for it. It's laborious and unneeded to outline exactly. I previously pushed a commit trying to tidy the rsnapshot code and add a contribute.md (DrHyde/rsnapshot#27). In that I said the maintainer should do the tidy, but from what I gathered `perltidy -nola -tabs -l 80 -io *.pl` was close to what conventions were predominantly being used in the perl code.

**Comment by bebehei** [comment]
> That the you guys outside of rsnapshot-maintainers know what's going on: This is what I've written to the list today/a few hours ago:

... but no answer yet. :disappointed:

**Comment by myrdd** [comment]
@bebehei I suggest to give them some more days, maybe unti saturday. If you got no answer then, I'd send a reminder and ask if they could state their opinion. I think you could get an answer on weekends more likely.

**Comment by bebehei** [comment]
https://github.com/DrHyde/rsnapshot/blob/master/AUTHORS#L28-L29

**Comment by bebehei** [comment]
https://github.com/rsnapshot/rsnapshot

Tätaräää!!! I've got it. We've got an organisation and I'm member of it. If you could participate at #53 it would be great and we could start fast!
